### ISSUE TITLE
Demo or example on how to use this?

### ISSUE THREAD

**Issue by keyjm** [BelAn97/mocha-rp-agent#2]
Hi,

I am very new to javascript world and mochajs and can't get figure out how to get this to work. I have tried putting the sample json (with real values) in mocha.opts file but always see an error 

`Warning: Could not find any test files matching pattern:`

As I understand mocha.opts file format is similar to yaml so I am confused how to configure your library with mochajs I would appreciate if you can put a small demo project.

**Comment by alprotasov** [comment]
I didn't set up this reporter as a separate module (I created issue but no-one answered me).
As a workaround I created "reporter" folder and copy-pasted two files mocha-reportportal-reporter and seecificUtils from this repo there.
in mocha.opts (I put it in the test folder) I put
--colors
--timeout 180000 //requirements of my tests, you can put your value
--reporter reporter/mocha-reportportal-reporter.js --reporter-options token=<TOKEN_FROM_REPORTPORTA_USER>,endpoint=<URL_of_reportportal>/api/v1,launch=LAUNCH_NAME,project=PROJECT_NAME,attachScreenshots=false,showPassedHooks=false

in package.json I put
"scripts": {
    "test": "mocha test/**/test*.js "
  },

npm test to run tests
It worked for me

**Comment by keyjm** [comment]
Thanks much. I will give this a try

**Comment by BelAn97** [comment]
Hi,
Could you try this example:
https://github.com/BelAn97/protractor-ext-po
You should modify "protractor-conf-rp.js" mochaReportportalAgentReporterOptions and run the test from command line "grunt  rp"
