### ISSUE TITLE
 Agent is giving an error "Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by mvitiuk** [BelAn97/mocha-rp-agent#4]
I'm using this agent with mocha that is running programatically for api testing (no screenshots).
I have config as 

> {
>   "reporterEnabled": "spec, mocha-reportportal-agent",
> 
>   "reporterOptions": {
>     "token": "<token>",
>     "endpoint": "http://localhost:8080/api/v1",
>     "launch": "api_mocha",
>     "project": "api-test",
>     "tags": ["api"],
>     "attachScreenshots": false,
>     "showPassedHooks": false
>   }
> }

but each time when test is failing I see 

> error (node:55662) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined

This is happening because my tests seems to not have name which can not be replaced.
My fileObj from here  

> if (fileObj !== null) {

https://github.com/BelAn97/mocha-rp-agent/blob/6c6f87261f439952bdada82e7a22fa97146c2522/lib/mocha-reportportal-reporter.js#L204

is 

> { uniqueId: 'auto:09a623964ad0a919d9e09db7a8720985',
>   id: '5be15f699daec2000146781a' }

Changing line to 

> if (fileObj.name) {

solving the issue.

Can this be fixed?

**Comment by BelAn97** [comment]
Thanks! Done.
